[repository]
name = "plone-recyclebin"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "semver"
container_images_prefix = "ghcr.io/plone/plone-recyclebin"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "plone.recyclebin"
path = "backend"
code_path = "src/plone/recyclebin"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend.package]
name = "volto-recyclebin"
path = "frontend/packages/volto-recyclebin"
code_path = "src"
changelog = "frontend/packages/volto-recyclebin/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-recyclebin/towncrier.toml"
base_package = "@plone/volto"
publish = true

[cookieplone]
template = "monorepo_addon"
template_version = "c28119899af4373696232a54210fac17fcf79dc7"
generated_date = "2026-08-04 21:03:32"
