# syntax=docker/dockerfile:1
ARG PLONE_VERSION=6.2.1
FROM plone/server-builder:${PLONE_VERSION} AS builder

WORKDIR /app


# Add local code
COPY scripts/ scripts/
COPY . src

# Install local requirements and pre-compile mo files
RUN <<EOT
    set -e
    bin/pip install mxdev uv
    sed -i 's/-e .\[test\]/./g' src/mx.ini
    cd /app/src
    # remove potentially existing virtualenv from local build
    rm -rf .venv
    ../bin/mxdev -c mx.ini
    ../bin/uv pip install -r requirements-mxdev.txt
    ../bin/python /compile_mo.py
EOT

FROM plone/server-acceptance:${PLONE_VERSION}

LABEL maintainer="Plone Community <info@plone.org>" \
      org.label-schema.name="plone-recyclebin-acceptance" \
      org.label-schema.description="Plone Recycle Bin backend acceptance image." \
      org.label-schema.vendor="Plone Community"

ENV CONFIGURE_PACKAGES="plone.restapi,plone.volto,plone.volto.cors,plone.recyclebin"
ENV APPLY_PROFILES="plone.recyclebin:default"

# Copy /app from builder
COPY --from=builder /app /app

RUN <<EOT
    ln -s /data /app/var
EOT
