export const GET_RECYCLE_BIN = 'GET_RECYCLE_BIN';
export const GET_RECYCLE_BIN_ITEM = 'GET_RECYCLE_BIN_ITEM';
export const RESTORE_RECYCLE_BIN_ITEM = 'RESTORE_RECYCLE_BIN_ITEM';
export const PURGE_RECYCLE_BIN_ITEM = 'PURGE_RECYCLE_BIN_ITEM';
export const EMPTY_RECYCLE_BIN = 'EMPTY_RECYCLE_BIN';
export const RESET_RECYCLE_BIN_OPERATION = 'RESET_RECYCLE_BIN_OPERATION';
